### ISSUE TITLE
jsonp请求在加callback的时候直接加的'?'，而没有判断是否已有其他参数

### ISSUE THREAD

**Issue by takashiki** [snandy/io#2]
![f3pic96 6kf gzx6hwhziia](https://cloud.githubusercontent.com/assets/3853614/10444123/57b0c594-7195-11e5-8fad-ec35ebe1e6cd.jpg)

在已有其他参数时，应该加'&'分隔符

**Comment by snandy** [comment]
多谢，已修复。
